title: Virtual AI Patient Docs
description: Product, architecture, and technical documentation for the Virtual AI Patient project.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

url: "https://virtual-ai-patient.github.io"
baseurl: "/platform"

color_scheme: light

nav_enabled: true
aux_links:
  "GitHub repository":
    - "https://github.com/virtual-ai-patient/platform"

collections:
  qa:
    output: true
    permalink: /qa/:name
  sprints:
    output: true
    permalink: /sprints/:path

